# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gapseq_plot_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotUI(object):
    def setupUi(self, PlotUI):
        PlotUI.setObjectName("PlotUI")
        PlotUI.resize(400, 173)
        self.verticalLayout = QtWidgets.QVBoxLayout(PlotUI)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(PlotUI)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(PlotUI)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.plot_mode = QtWidgets.QComboBox(PlotUI)
        self.plot_mode.setObjectName("plot_mode")
        self.plot_mode.addItem("")
        self.plot_mode.addItem("")
        self.plot_mode.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.plot_mode)
        self.verticalLayout.addLayout(self.formLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(PlotUI)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(PlotUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(20, 0))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.plot_localisation_number = QtWidgets.QSlider(PlotUI)
        self.plot_localisation_number.setOrientation(QtCore.Qt.Horizontal)
        self.plot_localisation_number.setObjectName("plot_localisation_number")
        self.gridLayout.addWidget(self.plot_localisation_number, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(PlotUI)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.plot_frame_number = QtWidgets.QSlider(PlotUI)
        self.plot_frame_number.setOrientation(QtCore.Qt.Horizontal)
        self.plot_frame_number.setObjectName("plot_frame_number")
        self.gridLayout.addWidget(self.plot_frame_number, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(PlotUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(20, 0))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(PlotUI)
        QtCore.QMetaObject.connectSlotsByName(PlotUI)

    def retranslateUi(self, PlotUI):
        _translate = QtCore.QCoreApplication.translate
        PlotUI.setWindowTitle(_translate("PlotUI", "Form"))
        self.label.setText(_translate("PlotUI", "Plot Settings"))
        self.label_2.setText(_translate("PlotUI", "Plot Mode"))
        self.plot_mode.setItemText(0, _translate("PlotUI", "Localisation Image"))
        self.plot_mode.setItemText(1, _translate("PlotUI", "Graph Image(s)"))
        self.plot_mode.setItemText(2, _translate("PlotUI", "All Images"))
        self.label_3.setText(_translate("PlotUI", "Localisation Number"))
        self.label_4.setText(_translate("PlotUI", "0"))
        self.label_5.setText(_translate("PlotUI", "Frame Number"))
        self.label_6.setText(_translate("PlotUI", "0"))
